## essential functionality

In [3]:
import numpy as np
import pandas as pd

### 1.Reindexing

In [5]:
obj=pd.Series([4.5,2.3,-5.6,9.8],index=['d','b','a','c'])

In [6]:
obj

d    4.5
b    2.3
a   -5.6
c    9.8
dtype: float64

In [10]:
obj.reindex(['a','b','c','d'])

a   -5.6
b    2.3
c    9.8
d    4.5
dtype: float64

In [17]:
obj1=pd.Series(['blue','red','ehite'],index=[0,2,4])

In [18]:
obj1

0     blue
2      red
4    ehite
dtype: object

In [20]:
obj1.reindex(np.arange(6),method='ffill')

0     blue
1     blue
2      red
3      red
4    ehite
5    ehite
dtype: object

In [26]:
frame1=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['up','mp','ap'])

In [27]:
frame1

up  mp  ap
a   0   1   2
c   3   4   5
d   6   7   8

In [28]:
frame1.reindex(['a','b','c','d'])

up   mp   ap
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [32]:
state=['up','mp','delhi']

In [33]:
frame1.reindex(columns=state)

up  mp  delhi
a   0   1    NaN
c   3   4    NaN
d   6   7    NaN

### dropping entry from axix

In [35]:
obj2=pd.Series(np.arange(6),index=['a','b','c','d','e','f'])

In [36]:
obj2

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [43]:
obj2.index.name='sr'

In [41]:
obj2

sr
a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [45]:
obj2.drop('a')

sr
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [48]:
obj2.drop(['f','e'])

sr
a    0
b    1
c    2
d    3
dtype: int32

In [49]:
frame2=pd.DataFrame(np.arange(16).reshape(4,4),index=['a','b','c','d'],columns=['up','mp','ap','wb'])

In [50]:
frame2

up  mp  ap  wb
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [51]:
frame2.drop(['a','c'])

up  mp  ap  wb
b   4   5   6   7
d  12  13  14  15

In [53]:
frame2.drop('mp',axis=1)

up  ap  wb
a   0   2   3
b   4   6   7
c   8  10  11
d  12  14  15

In [55]:
frame2.drop(['mp','ap'],axis='columns')

up  wb
a   0   3
b   4   7
c   8  11
d  12  15

### indexing selection and filtering

In [57]:
obj3=pd.Series(np.arange(6),index=['a','b','c','d','e','f'])

In [58]:
obj3

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [59]:
obj3['d']

3

In [60]:
obj3['a':'e']

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [62]:
obj3['a':'b']=5

In [63]:
obj3

a    5
b    5
c    2
d    3
e    4
f    5
dtype: int32

In [64]:
frame3=pd.DataFrame(np.arange(16).reshape(4,4),index=['a','b','c','d'],columns=['one','two','three','four'])

In [65]:
frame3

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [67]:
frame3['three']

a     2
b     6
c    10
d    14
Name: three, dtype: int32

In [68]:
frame3[:2]

one  two  three  four
a    0    1      2     3
b    4    5      6     7

In [69]:
frame3>6

one    two  three   four
a  False  False  False  False
b  False  False  False   True
c   True   True   True   True
d   True   True   True   True

In [70]:
frame3[frame3<5]=10

In [71]:
frame3

one  two  three  four
a   10   10     10    10
b   10    5      6     7
c    8    9     10    11
d   12   13     14    15

### selection with location

In [75]:
frame4=pd.DataFrame(np.arange(16).reshape(4,4),index=['a','b','c','d'],columns=['one','two','three','four'])

In [76]:
frame4

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [78]:
frame4.loc['a',['one','three']]

one      0
three    2
Name: a, dtype: int32

In [79]:
frame4.iloc[2,[2,1,0]]

three    10
two       9
one       8
Name: c, dtype: int32

In [80]:
frame4.iloc[2]

one       8
two       9
three    10
four     11
Name: c, dtype: int32

In [82]:
frame4.iloc[[1,2],[0,1,2]]

one  two  three
b    4    5      6
c    8    9     10

### arithmatic operation and data Allignment

In [84]:
s1=pd.Series([7.3,-2.3,1.1,7.3,2.34,3.1],index=['a','b','c','d','e','e'])

In [85]:
s2=pd.Series([7.3,-2.32,13.1,37.3,12.34,13.1],index=['a','b','e','d','e','f'])

In [86]:
s1+s2

a    14.60
b    -4.62
c      NaN
d    44.60
e    15.44
e    14.68
e    16.20
e    15.44
f      NaN
dtype: float64

In [93]:
df1=pd.DataFrame(np.arange(16).reshape(4,4),index=['a','b','c','d'],columns=['one','two','three','four'])

In [94]:
df2=pd.DataFrame(np.arange(20).reshape(5,4),index=['a','b','d','c','e'],columns=['one','two','three','four'])

In [95]:
df1+df2

one   two  three  four
a   0.0   2.0    4.0   6.0
b   8.0  10.0   12.0  14.0
c  20.0  22.0   24.0  26.0
d  20.0  22.0   24.0  26.0
e   NaN   NaN    NaN   NaN

In [96]:
f1=pd.DataFrame(np.arange(16).reshape(4,4),columns=list('abcd'))

In [97]:
f2=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))

In [98]:
f2.loc[1,'b']=np.nan

In [99]:
f1+f2

a     b   c   d   e
0   0   2.0   4   6 NaN
1   9   NaN  13  15 NaN
2  18  20.0  22  24 NaN
3  27  29.0  31  33 NaN

In [101]:
f1.add(f2,fill_value=0)

a     b   c   d     e
0   0   2.0   4   6   4.0
1   9   5.0  13  15   9.0
2  18  20.0  22  24  14.0
3  27  29.0  31  33  19.0

In [102]:
1/f1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909
3  0.083333  0.076923  0.071429  0.066667

In [107]:
f1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909
3  0.083333  0.076923  0.071429  0.066667

In [105]:
f1.reindex(columns=f2.columns,fill_value=0)

a   b   c   d  e
0   0   1   2   3  0
1   4   5   6   7  0
2   8   9  10  11  0
3  12  13  14  15  0

### Operation between DataFrame and Series

In [109]:
arr=np.arange(12.).reshape((3,4))

In [110]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [111]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [112]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [113]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['mp','up','ap','wb'])

In [114]:
frame

b     d     e
mp  0.0   1.0   2.0
up  3.0   4.0   5.0
ap  6.0   7.0   8.0
wb  9.0  10.0  11.0

In [115]:
series=frame.iloc[0]

In [116]:
series

b    0.0
d    1.0
e    2.0
Name: mp, dtype: float64

In [117]:
frame-series

b    d    e
mp  0.0  0.0  0.0
up  3.0  3.0  3.0
ap  6.0  6.0  6.0
wb  9.0  9.0  9.0

In [119]:
series2=pd.Series(range(3),index=list('bef'))

In [121]:
series2

b    0
e    1
f    2
dtype: int32

In [122]:
frame+series2

b   d     e   f
mp  0.0 NaN   3.0 NaN
up  3.0 NaN   6.0 NaN
ap  6.0 NaN   9.0 NaN
wb  9.0 NaN  12.0 NaN

In [123]:
series3=frame['d']

In [124]:
series3

mp     1.0
up     4.0
ap     7.0
wb    10.0
Name: d, dtype: float64

In [126]:
frame.sub(series3,axis='index')

b    d    e
mp -1.0  0.0  1.0
up -1.0  0.0  1.0
ap -1.0  0.0  1.0
wb -1.0  0.0  1.0

In [135]:
f=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['up','mp','ap','wb'])

In [136]:
f

b         d         e
up  0.882790  0.713687  0.725038
mp -1.255146  0.054373  2.053293
ap -0.612094  0.212115 -0.196926
wb  0.400131 -1.322893  0.931414

In [137]:
np.abs(f)

b         d         e
up  0.882790  0.713687  0.725038
mp  1.255146  0.054373  2.053293
ap  0.612094  0.212115  0.196926
wb  0.400131  1.322893  0.931414

In [141]:
a=lambda x:x.max()-x.min()

In [142]:
f.apply(a)

b    2.137936
d    2.036580
e    2.250219
dtype: float64

In [143]:
f.apply(a,axis='columns')

up    0.169103
mp    3.308439
ap    0.824208
wb    2.254307
dtype: float64

In [1]:
def a(x):
    
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [2]:
f.apply(a)

NameError: name 'f' is not defined

### sorting and ranking

In [157]:
f3=pd.Series(np.arange(4),index=list('acbd'))

In [158]:
f3

a    0
c    1
b    2
d    3
dtype: int32

In [159]:
f3.sort_index()

a    0
b    2
c    1
d    3
dtype: int32

In [164]:
f4=pd.DataFrame(np.arange(16).reshape(4,4),columns=list('1234'),index=list('dcba'))

In [165]:
f4

1   2   3   4
d   0   1   2   3
c   4   5   6   7
b   8   9  10  11
a  12  13  14  15

In [166]:
f4.sort_index()

1   2   3   4
a  12  13  14  15
b   8   9  10  11
c   4   5   6   7
d   0   1   2   3

In [180]:
f4.sort_index(axis=1,ascending=False)

4   3   2   1
d   3   2   1   0
c   7   6   5   4
b  11  10   9   8
a  15  14  13  12

In [178]:
f4.sort_values(by=2)

KeyError: 2