In [1]:
import numpy as np
   

In [2]:
data=np.random.randn(2,3)

In [3]:
data

array([[ 1.0115292 ,  1.48739691, -0.95032119],
       [-0.47594549,  0.58920374, -0.574047  ]])

In [15]:
data*10


array([[-0.25336088, -7.9937798 ,  1.04784776],
       [-0.27058378,  6.82229828,  3.92366406]])

In [7]:
data.dtype

dtype('float64')

In [8]:
data+data

array([[ 2.79179269, -0.07547318, -1.2649951 ],
       [-0.84499193, -1.17013958,  2.52494355]])

In [9]:
data.shape

(2, 3)

In [10]:
b=np.arange(10)

In [11]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
data1=(10,20,3.2,34,12,45)

In [11]:
a1=np.array(data1)

In [12]:
a1

array([ 10. ,  20. ,   3.2,  34. ,  12. ,  45. ])

In [29]:
data2=([10,20,30,40],[50,60,70,80])

In [30]:
a2=np.array(data2)

In [31]:
a2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [25]:
a2.size

8

In [26]:
a2.shape

(2, 4)

In [27]:
a2.dtype

dtype('int32')

In [28]:
a2.ndim

2

In [19]:
data3=([10,20,30,40],[50,60,70,80],[90,100,110,120])
 

In [20]:
a3=np.array(data3)

In [23]:
a3

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [24]:
a3.shape

(3, 4)

In [27]:
a3.ndim

2

In [30]:
a4=np.zeros(5)

In [32]:
a5=np.empty((2,3,2))

In [33]:
a4

array([ 0.,  0.,  0.,  0.,  0.])

In [34]:
a5

array([[[  1.20560090e-311,   2.81617418e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  1.89146896e-307,   2.92966904e-033]],

       [[  5.33243502e-091,   1.25768969e-075],
        [  2.32498319e-057,   4.00009585e+175],
        [  6.48224659e+170,   4.93432906e+257]]])

In [35]:
a4=np.zeros((2,3))

In [36]:
a4

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [38]:
a6=np.arange(10)

In [39]:
a6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a7=np.ones((2,3,3),dtype=np.float64)

In [37]:
a7

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [38]:
a7.ndim

3

In [39]:
a7.dtype

dtype('float64')

In [40]:
a7.astype(np.int16)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [58]:
a8=np.array([[1,2,3,4],[5,6,7,8] ],dtype=np.float64)

In [59]:
a8*a8

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.]])

In [60]:
a8

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [61]:
a9=np.array([[11,2,32,4],[51,6,7,8] ],dtype=np.float64)

In [ ]:
# airthmatic operation in numpy array

In [62]:
a8>=a9

array([[False,  True, False,  True],
       [False,  True,  True,  True]], dtype=bool)

In [63]:
#indexing and slicing


In [65]:
a10=np.arange(10)

In [66]:
a10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a10[2:8:2]

array([2, 4, 6])

In [70]:
a10[2:8:2]=10

In [72]:
a10

array([ 0,  1, 10,  3, 10,  5, 10,  7,  8,  9])

In [73]:
as1=a10[2:8:2]

In [75]:
as1[1]=29

In [76]:
a10

array([ 0,  1, 10,  3, 29,  5, 10,  7,  8,  9])

In [78]:
a11=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [88]:
a11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a11[2][2]

9

In [85]:
a11[2,2]

9

In [86]:
a11[:2,:1]

array([[1],
       [4]])

In [89]:
a11[:2,1]

array([2, 5])