In [1]:
# boolean indexing

In [1]:
import numpy as np

In [2]:
names=np.array(['satyam','shivam','sundram','satyam','dhanji','shubhji','virat'])

In [3]:
names

array(['satyam', 'shivam', 'sundram', 'satyam', 'dhanji', 'shubhji',
       'virat'],
      dtype='<U7')

In [4]:
data=np.random.randn(7,4)

In [5]:
data

array([[-0.21557172, -0.41762676,  1.87403909,  0.29776169],
       [-0.10426697,  1.66866014,  0.18343676, -0.71232231],
       [ 0.78397129,  0.40275397, -1.29152778,  0.21664572],
       [-0.22838845, -2.11295565, -1.01321126, -0.38092427],
       [ 0.55257821, -2.04880017, -0.13967998, -0.69889927],
       [-1.47315754,  0.26078015, -0.22798513,  1.33243456],
       [ 0.46058588, -1.37097729, -0.09189569,  0.28324275]])

In [6]:
names=='satyam'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [7]:
data[names=='satyam']

array([[-0.21557172, -0.41762676,  1.87403909,  0.29776169],
       [-0.22838845, -2.11295565, -1.01321126, -0.38092427]])

In [8]:
data[names=='satyam',2:]

array([[ 1.87403909,  0.29776169],
       [-1.01321126, -0.38092427]])

In [9]:
data[names=='satyam',3]

array([ 0.29776169, -0.38092427])

In [10]:
names!='satyam'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [11]:
data[names!='satyam']

array([[-0.10426697,  1.66866014,  0.18343676, -0.71232231],
       [ 0.78397129,  0.40275397, -1.29152778,  0.21664572],
       [ 0.55257821, -2.04880017, -0.13967998, -0.69889927],
       [-1.47315754,  0.26078015, -0.22798513,  1.33243456],
       [ 0.46058588, -1.37097729, -0.09189569,  0.28324275]])

In [12]:
data[~(names=='satyam')]

array([[-0.10426697,  1.66866014,  0.18343676, -0.71232231],
       [ 0.78397129,  0.40275397, -1.29152778,  0.21664572],
       [ 0.55257821, -2.04880017, -0.13967998, -0.69889927],
       [-1.47315754,  0.26078015, -0.22798513,  1.33243456],
       [ 0.46058588, -1.37097729, -0.09189569,  0.28324275]])

In [13]:
cond=names=='satyam'

In [14]:
data[~(cond)]

array([[-0.10426697,  1.66866014,  0.18343676, -0.71232231],
       [ 0.78397129,  0.40275397, -1.29152778,  0.21664572],
       [ 0.55257821, -2.04880017, -0.13967998, -0.69889927],
       [-1.47315754,  0.26078015, -0.22798513,  1.33243456],
       [ 0.46058588, -1.37097729, -0.09189569,  0.28324275]])

In [15]:
match=(names=='satyam')|(names=='virat')

In [16]:
match

array([ True, False, False,  True, False, False,  True], dtype=bool)

In [17]:
data[match]

array([[-0.21557172, -0.41762676,  1.87403909,  0.29776169],
       [-0.22838845, -2.11295565, -1.01321126, -0.38092427],
       [ 0.46058588, -1.37097729, -0.09189569,  0.28324275]])

In [18]:
data1=data[data<0].copy()  # this is a copy of data if we chane anything init no effect on old data

In [19]:
data1=0

In [20]:
data2=data[data<0]=0  # here we change data this effect the main data

In [21]:
data

array([[ 0.        ,  0.        ,  1.87403909,  0.29776169],
       [ 0.        ,  1.66866014,  0.18343676,  0.        ],
       [ 0.78397129,  0.40275397,  0.        ,  0.21664572],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.55257821,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.26078015,  0.        ,  1.33243456],
       [ 0.46058588,  0.        ,  0.        ,  0.28324275]])

In [22]:
# fancy indexing

In [23]:
a=np.empty((8,4))

In [24]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
for i in range(8):
    a[i]=i


In [26]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [27]:
a[[0,3,2,7]]   # passing a list in array index

array([[ 0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.],
       [ 2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.]])

In [28]:
a[[-1,-7,-3,-2,-6]] # we can also pass negative indexing

array([[ 7.,  7.,  7.,  7.],
       [ 1.,  1.,  1.,  1.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 2.,  2.,  2.,  2.]])

In [29]:
a[[1,2,3],[1,2,3]]

array([ 1.,  2.,  3.])

In [30]:
a1=np.arange(15).reshape((3,5))

In [31]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a1.T   # transpose of matrix

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [33]:
a2=np.random.randn(6,3)

In [34]:
a2

array([[-0.11990532,  1.1994652 ,  1.1904096 ],
       [ 1.05872812, -0.0022807 , -0.21833609],
       [ 0.11716428,  0.1109865 , -1.15243338],
       [-0.19145833, -0.98600608,  1.01694225],
       [-0.00539286, -1.22880877, -0.70843212],
       [ 0.48759271,  0.43845387,  0.18686957]])

In [35]:
a2.T

array([[-0.11990532,  1.05872812,  0.11716428, -0.19145833, -0.00539286,
         0.48759271],
       [ 1.1994652 , -0.0022807 ,  0.1109865 , -0.98600608, -1.22880877,
         0.43845387],
       [ 1.1904096 , -0.21833609, -1.15243338,  1.01694225, -0.70843212,
         0.18686957]])

In [36]:
a3=np.dot(a2.T,a2)  #matrix multiplication

In [37]:
a3

array([[ 1.42344201,  0.27595952, -0.60868437],
       [ 0.27595952,  4.12546074,  1.25019835],
       [-0.60868437,  1.25019835,  4.3638162 ]])

In [38]:
a3.swapaxes(0,1) # this method is not understand compleate example by book

array([[ 1.42344201,  0.27595952, -0.60868437],
       [ 0.27595952,  4.12546074,  1.25019835],
       [-0.60868437,  1.25019835,  4.3638162 ]])

In [39]:
#universal function

In [40]:
a4=np.arange(10)

In [41]:
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.sqrt(a4)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [43]:
np.exp(a4)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [44]:
x=np.random.randn(8)

In [45]:
x

array([ 0.13691701,  0.02463612,  0.6207251 , -0.64196551,  1.20610529,
       -0.4927524 ,  0.99000671, -0.93621118])

In [46]:
y=np.random.randn(8)

In [47]:
y

array([-0.70197135,  1.04632344, -0.58711871,  1.0763735 , -0.45436286,
        0.34144316,  0.70946589,  0.10798166])

In [48]:
np.maximum(x,y)

array([ 0.13691701,  1.04632344,  0.6207251 ,  1.0763735 ,  1.20610529,
        0.34144316,  0.99000671,  0.10798166])

In [49]:
a5=np.random.randn(7)*5

In [50]:
a5

array([-0.48863856,  9.27033206, -1.54664275,  8.16256201, -2.77596261,
       -9.47899233, -3.91908544])

In [51]:
remainder_part,whole_part=np.modf(a5)

In [52]:
whole_part

array([-0.,  9., -1.,  8., -2., -9., -3.])

In [53]:
remainder_part

array([-0.48863856,  0.27033206, -0.54664275,  0.16256201, -0.77596261,
       -0.47899233, -0.91908544])

In [54]:
np.sqrt(a5)

C:\Users\satya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  3.044722  ,         nan,  2.85701978,         nan,
               nan,         nan])