In [1]:
#array oriented programming with array(numericalpython)

In [2]:
import numpy as np

In [3]:
points=np.arange(-5,5,0.01)

In [4]:
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [5]:
x,y=np.meshgrid(points,points) # it give two 1D array and produce 2D matrix

In [6]:
y

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [7]:
z=np.sqrt(x**2,y**2)

In [8]:
z

array([[ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99],
       [ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99],
       [ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99],
       [ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99],
       [ 5.  ,  4.99,  4.98, ...,  4.97,  4.98,  4.99]])

In [9]:
# use matplotlib to visulization of given function

In [10]:
import matplotlib.pyplot as plt

In [11]:
plt.imshow(z,cmap=plt.cm.gray); plt.colorbar()

In [12]:
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2+y^2}$ for a grid of values')

In [16]:
#example 2

In [19]:
p=np.arange(15)

In [20]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
x1,y1=np.meshgrid(p,p)

In [22]:
y1

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [14, 14, 14, 14, 14, 14, 14

In [24]:
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6

In [27]:
z=np.sqrt(x1**2+y1**2)

In [28]:
z

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ,   5.        ,   6.        ,   7.        ,
          8.        ,   9.        ,  10.        ,  11.        ,
         12.        ,  13.        ,  14.        ],
       [  1.        ,   1.41421356,   2.23606798,   3.16227766,
          4.12310563,   5.09901951,   6.08276253,   7.07106781,
          8.06225775,   9.05538514,  10.04987562,  11.04536102,
         12.04159458,  13.03840481,  14.03566885],
       [  2.        ,   2.23606798,   2.82842712,   3.60555128,
          4.47213595,   5.38516481,   6.32455532,   7.28010989,
          8.24621125,   9.21954446,  10.19803903,  11.18033989,
         12.16552506,  13.15294644,  14.14213562],
       [  3.        ,   3.16227766,   3.60555128,   4.24264069,
          5.        ,   5.83095189,   6.70820393,   7.61577311,
          8.54400375,   9.48683298,  10.44030651,  11.40175425,
         12.36931688,  13.34166406,  14.31782106],
       [  4.        ,   4.12

In [29]:
#to show  on image it is used matplotlib

In [30]:
# expessing conditional logic as array Operation

In [37]:
x2=np.arange(1.1,1.6,0.1)

In [38]:
x2

array([ 1.1,  1.2,  1.3,  1.4,  1.5])

In [39]:
y2=np.array([2.1,2.2,2.3,2.4,2.5])

In [40]:
y2

array([ 2.1,  2.2,  2.3,  2.4,  2.5])

In [43]:
cond2=np.array([True, False, True, True, False])

In [44]:
result=[(x if c else y) for x,y,c in zip(x2,y2,cond2)]

In [45]:
result

[1.1000000000000001,
 2.2000000000000002,
 1.3000000000000003,
 1.4000000000000004,
 2.5]

In [46]:
result2=np.where(cond2,x2,y2)

In [47]:
result2

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [49]:
arr=np.random.randn(4,4)

In [50]:
arr

array([[-1.11301175, -0.85052698,  0.2198847 , -0.09995048],
       [-1.01649237, -0.10515645, -0.31065717,  0.20063467],
       [ 0.78870501, -0.4879033 ,  0.16687453,  0.65101178],
       [ 0.06476415, -0.16607865,  0.66404834, -0.2756139 ]])

In [51]:
np.where(arr>0,2,-2)

array([[-2, -2,  2, -2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2],
       [ 2, -2,  2, -2]])

In [52]:
np.where(arr>0,2,arr)

array([[-1.11301175, -0.85052698,  2.        , -0.09995048],
       [-1.01649237, -0.10515645, -0.31065717,  2.        ],
       [ 2.        , -0.4879033 ,  2.        ,  2.        ],
       [ 2.        , -0.16607865,  2.        , -0.2756139 ]])

In [53]:
# mathmetical and statical method

In [54]:
p=np.arange(15).reshape(3,5)

In [55]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
p.ndim

2

In [57]:
p.mean()

7.0

In [58]:
np.mean(p)

7.0

In [59]:
p.sum()

105

In [66]:
p.mean(axis=1) #axis 0 means column wise and axis 1 means row wise

array([  2.,   7.,  12.])

In [67]:
p.sum(axis=0)

array([15, 18, 21, 24, 27])

In [73]:
q=np.arange(9).reshape(3,3)

In [74]:
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
q.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [77]:
q.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)