In [1]:
import numpy as np

In [2]:
#method for boolean array

In [3]:
arr=np.array([True,False,False,True,True])

In [4]:
arr.any()

True

In [5]:
arr.all()

False

In [6]:
# sorting in array

In [7]:
arr=np.random.randn(6)

In [8]:
arr

array([-0.46345773,  0.63947284,  0.64821748,  2.37189342,  1.36568379,
       -0.73880762])

In [9]:
arr.sort()

In [10]:
arr

array([-0.73880762, -0.46345773,  0.63947284,  0.64821748,  1.36568379,
        2.37189342])

In [25]:
arr=np.random.randn(5,3)

In [26]:
arr

array([[ 0.62755746,  2.37729781,  0.13776757],
       [-1.06442844,  0.32812926, -0.31226892],
       [-0.68581277,  0.84069375, -0.21020001],
       [ 0.31742307,  0.88941085,  0.37652478],
       [-0.1437986 ,  0.47647496,  0.27504266]])

In [27]:
arr.sort(0)

In [28]:
arr

array([[-1.06442844,  0.32812926, -0.31226892],
       [-0.68581277,  0.47647496, -0.21020001],
       [-0.1437986 ,  0.84069375,  0.13776757],
       [ 0.31742307,  0.88941085,  0.27504266],
       [ 0.62755746,  2.37729781,  0.37652478]])

In [29]:
# unique and other set logic

In [32]:
names=np.array(["satyam","shivam","satyam","sundram","virat","sundram"])

In [34]:
np.unique(names)

array(['satyam', 'shivam', 'sundram', 'virat'],
      dtype='<U7')

In [36]:
sorted(set(names)) # pure python program

['satyam', 'shivam', 'sundram', 'virat']

In [37]:
#file input output with arrays

In [38]:
arr=np.arange(10)

In [39]:
np.save('new_array',arr)

In [41]:
np.load('new_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#linear alzebra

In [48]:
x=np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [49]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [50]:
y=np.array([[1,2],[2,3],[4,5]])

In [51]:
y

array([[1, 2],
       [2, 3],
       [4, 5]])

In [52]:
np.dot(x,y)

array([[ 17.,  23.],
       [ 38.,  53.]])

In [53]:
x.dot(y)

array([[ 17.,  23.],
       [ 38.,  53.]])

In [54]:
x@y

array([[ 17.,  23.],
       [ 38.,  53.]])

In [55]:
#Pseudorandom Number Generation

In [61]:
sample=np.random.normal(size=(4,4))

In [62]:
sample

array([[-1.49906868, -1.77345921, -0.78014535,  0.84442228],
       [-0.35580761, -0.100019  , -0.92454574, -0.25466087],
       [ 0.74571841, -0.94503122,  2.54346357,  0.08328208],
       [ 0.27952442, -0.64563284, -0.48500038,  0.3472982 ]])

In [64]:
from random import normalvariate

In [65]:
n=1000

In [67]:
%timeit samples=[normalvariate(0,1) for _ in range(n)]

2.97 ms ± 37.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [68]:
%timeit np.random.normal(size=n)

94.6 µs ± 776 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [69]:
# we can change random number generation seed by using given method

In [73]:
arr1=np.random.seed(1234) # what is the purpose not understand

In [76]:
rng=np.random.RandomState(1234)

In [78]:
rng.randn(3,5)

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873],
       [ 0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495],
       [ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737]])