Array with Array
Array with Scalars
Universal Array Function





In [2]:
import numpy as np

In [4]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
print(arr+arr)
print()

print(arr-arr)
print()

print(arr**2)

[ 0  2  4  6  8 10 12 14 16 18 20]

[0 0 0 0 0 0 0 0 0 0 0]

[  0   1   4   9  16  25  36  49  64  81 100]


Scalar

In [14]:
print(arr+100)

[100 101 102 103 104 105 106 107 108 109 110]


In [13]:
print(arr-100)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]


Universal function

In [9]:
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [10]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


In [11]:
print(np.sign(arr))

[0 1 1 1 1 1 1 1 1 1 1]


In [12]:
print(np.log(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


D:\Install folder\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
