Numpy Array

In [ ]:
import numpy as np
import numpy.random as randn

In [20]:
My_list=[1,2,3]
np.array(My_list)

array([1, 2, 3])

In [22]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr=np.arange(0,11,2) #It taken step size you want
print(arr)

[ 0  2  4  6  8 10]


In [17]:
zero=np.zeros((4,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
ones=np.ones((10,10))
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
linspace=np.linspace(0,5,10) #it taken number of point you want
print(linspace)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [28]:
eye=np.eye(4) #It give identity matrix
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
print(np.random.rand(5))
print(np.random.randn(4,4))
print(np.random.randint(0,100,10))

[0.0428199  0.44207247 0.97015583 0.02141381 0.46516995]
[[ 0.32408729  3.22969112  0.74760275 -0.46754532]
 [-0.50992085  1.58218623  0.13644021 -1.66600731]
 [ 1.22049018  0.91347326  0.62084326  0.50074193]
 [-0.45376558 -0.12207791  1.61787842  1.15514861]]
[83 94 76 28 97 24 54 42 25 87]


In [29]:
arr=np.arange(25)
print(arr)

ranarr=np.random.randint(0,100,10)
print(ranarr)

arr.reshape(5,5)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[91 30 94 98 76  0 19 76 87 55]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
print(arr.max()) #returnmaxvalue
print(arr.min()) #returnminvalue


24
0


In [35]:
print(arr.argmax()) #returnindexofmaxvalue
print(arr.argmin()) #returnindexofminvalue


24
0


In [38]:
print(arr.shape) #returnshape

print(arr.dtype) #returndatatpeofarray

(25,)
int32


In [40]:
from numpy.random import randint
randint(2,5,3)

array([3, 3, 2])

Good Job