Numpy indexing

In [31]:
import numpy as np
import numpy.random as randn

In [32]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [33]:
print(arr[1:5])

[1 2 3 4]


In [34]:
print(arr[1:])

[ 1  2  3  4  5  6  7  8  9 10]


numpy is different from list because we brocost value in numpy


In [35]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [36]:
arr=np.arange(0,11)
print(arr[0:5])


[0 1 2 3 4]


In [37]:
slice_of_arr=arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [38]:
slice_of_arr=99
print(slice_of_arr)
print(arr)


99
[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
arr_copy=arr.copy()
print(arr_copy)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [40]:
print(arr_copy[:])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [41]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [42]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [43]:
print(arr_2d[0])

[ 5 10 15]


In [44]:
print(arr_2d[1][2])

30


In [45]:
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [47]:
arr=np.arange(1,11)
print(arr>5)


[False False False False False  True  True  True  True  True]


In [48]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [50]:
bool_arr=arr>5
print(arr[bool_arr])

[ 6  7  8  9 10]


In [53]:
arr_2d=np.arange(50).reshape(5,10)


In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
print(arr_2d[1:3,3:5])

[[13 14]
 [23 24]]
